### ISSUE TITLE
Postgres connection bug

### ISSUE THREAD

**Issue by alcidesmig** [jmoiron/sqlx#741]
Hi!

After exactly 10 queries in the Postgres database, the db stops answering and the request does not end. The connection is also not cut by the timeout.

I'm running one Postgres docker container, using this service in docker-compose:

```
  db-proxy-idp:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: "-c logging_collector=on -c log_statement=all -c log_filename=p.log"
```

In the logs, the requests are logged normally until the 10th request, after this more logs are not created. If I drop my application and start it again, then I can make 10 requests again.

What could it be?

Thank you for the attention.
